/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as LayoutRootRouteImport } from './app/routes/_layout/_root'
import { Route as LayoutIndexRouteImport } from './app/routes/_layout/index'
import { Route as LayoutAuctionsAuctionIdIndexRouteImport } from './app/routes/_layout/auctions/$auctionId/index'
import { Route as LayoutAuctionsAuctionIdBetsRouteImport } from './app/routes/_layout/auctions/$auctionId/bets'

const LayoutRootRoute = LayoutRootRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRootRoute,
} as any)
const LayoutAuctionsAuctionIdIndexRoute =
  LayoutAuctionsAuctionIdIndexRouteImport.update({
    id: '/auctions/$auctionId/',
    path: '/auctions/$auctionId/',
    getParentRoute: () => LayoutRootRoute,
  } as any)
const LayoutAuctionsAuctionIdBetsRoute =
  LayoutAuctionsAuctionIdBetsRouteImport.update({
    id: '/auctions/$auctionId/bets',
    path: '/auctions/$auctionId/bets',
    getParentRoute: () => LayoutRootRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/auctions/$auctionId/bets': typeof LayoutAuctionsAuctionIdBetsRoute
  '/auctions/$auctionId/': typeof LayoutAuctionsAuctionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/auctions/$auctionId/bets': typeof LayoutAuctionsAuctionIdBetsRoute
  '/auctions/$auctionId': typeof LayoutAuctionsAuctionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRootRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/auctions/$auctionId/bets': typeof LayoutAuctionsAuctionIdBetsRoute
  '/_layout/auctions/$auctionId/': typeof LayoutAuctionsAuctionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auctions/$auctionId/bets' | '/auctions/$auctionId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auctions/$auctionId/bets' | '/auctions/$auctionId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/_layout/auctions/$auctionId/bets'
    | '/_layout/auctions/$auctionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRootRoute: typeof LayoutRootRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRootRoute
    }
    '/_layout/auctions/$auctionId/': {
      id: '/_layout/auctions/$auctionId/'
      path: '/auctions/$auctionId'
      fullPath: '/auctions/$auctionId/'
      preLoaderRoute: typeof LayoutAuctionsAuctionIdIndexRouteImport
      parentRoute: typeof LayoutRootRoute
    }
    '/_layout/auctions/$auctionId/bets': {
      id: '/_layout/auctions/$auctionId/bets'
      path: '/auctions/$auctionId/bets'
      fullPath: '/auctions/$auctionId/bets'
      preLoaderRoute: typeof LayoutAuctionsAuctionIdBetsRouteImport
      parentRoute: typeof LayoutRootRoute
    }
  }
}

interface LayoutRootRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAuctionsAuctionIdBetsRoute: typeof LayoutAuctionsAuctionIdBetsRoute
  LayoutAuctionsAuctionIdIndexRoute: typeof LayoutAuctionsAuctionIdIndexRoute
}

const LayoutRootRouteChildren: LayoutRootRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAuctionsAuctionIdBetsRoute: LayoutAuctionsAuctionIdBetsRoute,
  LayoutAuctionsAuctionIdIndexRoute: LayoutAuctionsAuctionIdIndexRoute,
}

const LayoutRootRouteWithChildren = LayoutRootRoute._addFileChildren(
  LayoutRootRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRootRoute: LayoutRootRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
