/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as AuctionsIndexRouteImport } from './app/routes/auctions/index'
import { Route as AuctionsAuctionIdRouteImport } from './app/routes/auctions/$auctionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIndexRoute = AuctionsIndexRouteImport.update({
  id: '/auctions/',
  path: '/auctions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsAuctionIdRoute = AuctionsAuctionIdRouteImport.update({
  id: '/auctions/$auctionId',
  path: '/auctions/$auctionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auctions/$auctionId': typeof AuctionsAuctionIdRoute
  '/auctions/': typeof AuctionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auctions/$auctionId': typeof AuctionsAuctionIdRoute
  '/auctions': typeof AuctionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auctions/$auctionId': typeof AuctionsAuctionIdRoute
  '/auctions/': typeof AuctionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auctions/$auctionId' | '/auctions/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auctions/$auctionId' | '/auctions'
  id: '__root__' | '/' | '/auctions/$auctionId' | '/auctions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuctionsAuctionIdRoute: typeof AuctionsAuctionIdRoute
  AuctionsIndexRoute: typeof AuctionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/': {
      id: '/auctions/'
      path: '/auctions'
      fullPath: '/auctions/'
      preLoaderRoute: typeof AuctionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$auctionId': {
      id: '/auctions/$auctionId'
      path: '/auctions/$auctionId'
      fullPath: '/auctions/$auctionId'
      preLoaderRoute: typeof AuctionsAuctionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuctionsAuctionIdRoute: AuctionsAuctionIdRoute,
  AuctionsIndexRoute: AuctionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
